### ISSUE TITLE
server keeps restarting

### ISSUE THREAD

**Issue by RyanSinger** [ahdinosaur/ssb-pub#37]
I think this may be related to the recent bug in ssb-links; but my pub keeps restarting and no longer works. How do I recover?

**Comment by sunjam** [comment]
I think the Docker build needs to be updated.  [Full details here](https://viewer.scuttlebot.io/%255JJIwkud9hizK8Bb2WYznfgKnRyHhrG5YBbw830d68Y%3D.sha256).

Copy-pasta follows:

Advisory: ssb-server crash fixed

A bug in [ssb-links](https://github.com/ssbc/ssb-links/) causes [ssb-server](https://github.com/ssbc/ssb-server/) to crash when handling certain messages recently published.

The main error message on crash is: Error: can only encode arrays.

This bug is fixed in ssb-links v3.0.10. If you encounter this crash, please reinstall/upgrade your ssb-server to get the updated ssb-links module.

It is possible a similar issue could exist with other #ssb plugins using [flumeview-links](https://github.com/flumedb/flumeview-links), in which case we will update this thread.

This issue primarily affects pub operators and users who run ssb-server directly. Users of apps that bundle ssb-server (e.g. Patchwork) are not affected.

There are no known security implications.

**Comment by ahdinosaur** [comment]
@sunjam is correct, an updating version is incoming. sorry for the delay. :purple_heart:

**Comment by ahdinosaur** [comment]
published a new version which should fix this: `v2.2.0` :tada: 

- updated to use `ssb-server@15.3.0`: https://github.com/ssbc/ssb-server/pull/739)
- updated to use Node 14

i've upgraded my own 3 pubs and they seem to be happy again. :smiley_cat:

**Comment by ahdinosaur** [comment]
ℹ️ the upgrade process for pub operators:  https://github.com/ahdinosaur/ssb-pub#update-ssb-pub-image

(if already using v2, otherwise see [v1 -> v2 upgrade guide](https://github.com/ahdinosaur/ssb-pub#migrating-from-v1-to-v2) )

```
docker pull ahdinosaur/ssb-pub
docker stop sbot
docker rm sbot
./create-sbot
```

check your pub is running with commands like:

```
docker logs sbot
./sbot whoami
```

**Comment by sunjam** [comment]
Can you please spell out the update process to get things working again.
It is failing for me, perhaps related to the helper. Unsure, but I'm still
offline

**Comment by ahdinosaur** [comment]
@sunjam: i might have been too optimistic. do you see an error, or just that you can't connect to your server from a client?

i also realized now invites are broken.

```
/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:123
      throw err
      ^
{
  message: 'resultHost.replace is not a function',
  name: 'TypeError',
  stack: 'TypeError: resultHost.replace is not a function\n' +
    '    at Object.stringify (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/plugins/net.js:124:31)\n' +
    '    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/compose.js:111:19\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object.stringify (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/compose.js:110:22)\n' +
    '    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/index.js:67:44\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object.stringify (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/index.js:67:10)\n' +
    '    at EventEmitter.getAddress (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/secret-stack/core.js:213:21)\n' +
    '    at EventEmitter.hooked [as getAddress] (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)\n' +
    '    at getInviteAddress (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:75:18)'
}
```

ughhhhh 😿

**Comment by sunjam** [comment]
Yes, updated pull fixed the pub running, but I see the exact same error you posted when creating invites.

**Comment by ahdinosaur** [comment]
okay, i think figured out the invite problem: https://github.com/ssb-js/secret-stack/issues/62.

the hotfix is to change your `~/ssb-pub-data/config` to match:

(change **connections.incoming.net[].external** from an array of strings to a string)

```diff
{
  "connections": {
    "incoming": {
      "net": [
        {
          "scope": "public",
          "host": "0.0.0.0",
-          "external": ["hostname.yourdomain.tld"],
+          "external": "hostname.yourdomain.tld",
          "transform": "shs",
          "port": 8008
        }
      ]
    },
    "outgoing": {
      "net": [
        {
          "transform": "shs"
        }
      ]
    }
  }
}
```

**Comment by ahdinosaur** [comment]
:heart_eyes_cat: 

![Screenshot from 2020-11-10 18-44-58](https://user-images.githubusercontent.com/719605/98632689-dcae5580-2384-11eb-805a-71976155fb7a.png)

**Comment by murilopolese** [comment]
Thanks for the hotfix, @ahdinosaur !! 🙏
